<a href="https://colab.research.google.com/github/NPSoto/PandasMastery/blob/main/concat_append8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install --upgrade pandas

     |████████████████████████████████| 9.9MB 2.9MB/s 
ERROR: google-colab 1.0.0 has requirement pandas~=1.1.0; python_version >= "3.0", but you'll have pandas 1.2.4 which is incompatible.
  Found existing installation: pandas 1.1.5
    Uninstalling pandas-1.1.5:
      Successfully uninstalled pandas-1.1.5


In [1]:
import pandas as pd
import numpy as np
pd.__version__

'1.2.4'

In [2]:
pd.options.display.float_format = '{:.2f}'.format

In [11]:
np.set_printoptions(precision=1)

In [4]:
np.random.rand()

0.5075209652660982

In [5]:
np.random.randn()

0.520610893629946

In [12]:
x1 = np.random.rand(2,5)*10

In [7]:
x1

array([[21.54, 33.75, 38.33, 76.28, 96.98],
       [74.48, 84.67, 24.76, 90.39, 56.53]])

In [8]:
x2 = np.random.rand(2,5)*-1
x2

array([[-0.51, -0.76, -0.69, -0.88, -0.02],
       [-0.27, -1.  , -0.96, -0.47, -0.46]])

In [13]:
np.concatenate([x1,x2])

array([[ 4.3,  2.3,  6.3,  0.5,  8.6],
       [ 1. ,  8.5,  4.7,  1.8,  1.9],
       [-0.5, -0.8, -0.7, -0.9, -0. ],
       [-0.3, -1. , -1. , -0.5, -0.5]])

In [14]:
np.concatenate([x1,x2]).shape

(4, 5)

In [16]:
np.concatenate([x1,x2],axis = 1).shape

(2, 10)

In [17]:
s1 = pd.Series(x1[0],index =['a','b','c','d','e'])
s1

a   4.35
b   2.28
c   6.27
d   0.49
e   8.56
dtype: float64

In [18]:
s2 = pd.Series(x2[0], index=['c','d','e','f','g'])
s2

c   -0.51
d   -0.76
e   -0.69
f   -0.88
g   -0.02
dtype: float64

In [19]:
pd.concat([s1,s2])

a    4.35
b    2.28
c    6.27
d    0.49
e    8.56
c   -0.51
d   -0.76
e   -0.69
f   -0.88
g   -0.02
dtype: float64

In [20]:
pd.concat([s1,s2], axis = 1 )

0     1
a 4.35   NaN
b 2.28   NaN
c 6.27 -0.51
d 0.49 -0.76
e 8.56 -0.69
f  NaN -0.88
g  NaN -0.02

In [22]:
s1.reset_index(drop=True)

0   4.35
1   2.28
2   6.27
3   0.49
4   8.56
dtype: float64

In [23]:
pd.concat([s1.reset_index(drop=True),s2.reset_index(drop=True)], axis = 1 )

0     1
0 4.35 -0.51
1 2.28 -0.76
2 6.27 -0.69
3 0.49 -0.88
4 8.56 -0.02

In [24]:
df1 = pd.DataFrame(np.random.rand(3,2)*10, columns=['a','b'])
df1

a    b
0 5.07 5.53
1 9.70 7.11
2 2.71 8.56

In [25]:
df2 = pd.DataFrame(np.random.rand(3,2)*-1, columns=['a','b'], index = [2,3,4])
df2

a     b
2 -0.21 -0.14
3 -0.11 -0.59
4 -0.14 -0.95

In [26]:
pd.concat([df1, df2])

a     b
0  5.07  5.53
1  9.70  7.11
2  2.71  8.56
2 -0.21 -0.14
3 -0.11 -0.59
4 -0.14 -0.95

In [27]:
pd.concat([df1, df2], axis=1)

a    b     a     b
0 5.07 5.53   NaN   NaN
1 9.70 7.11   NaN   NaN
2 2.71 8.56 -0.21 -0.14
3  NaN  NaN -0.11 -0.59
4  NaN  NaN -0.14 -0.95

In [28]:
pd.concat([df1, df2], axis=1, join= 'inner')

a    b     a     b
2 2.71 8.56 -0.21 -0.14

In [29]:
pd.concat([
      df1.reset_index (drop=True),
      df2.reset_index (drop=True)
      ],axis=1)

a    b     a     b
0 5.07 5.53 -0.21 -0.14
1 9.70 7.11 -0.11 -0.59
2 2.71 8.56 -0.14 -0.95

In [30]:
df1.append(df2).append(df2)

a     b
0  5.07  5.53
1  9.70  7.11
2  2.71  8.56
2 -0.21 -0.14
3 -0.11 -0.59
4 -0.14 -0.95
2 -0.21 -0.14
3 -0.11 -0.59
4 -0.14 -0.95

In [31]:
df1.T

0    1    2
a 5.07 9.70 2.71
b 5.53 7.11 8.56

In [32]:
df1.T.append(df2.T).T

a    b     a     b
0 5.07 5.53   NaN   NaN
1 9.70 7.11   NaN   NaN
2 2.71 8.56 -0.21 -0.14
3  NaN  NaN -0.11 -0.59
4  NaN  NaN -0.14 -0.95